taxi/urls.py
from django.urls import path

from .views import (
    index,
    CarListView,
    CarDetailView,
    CarCreateView,
    CarUpdateView,
    CarDeleteView,
    DriverListView,
    DriverDetailView,
    DriverCreateView,
    DriverLicenseUpdate,
    DriverDeleteView,
    ManufacturerListView,
    ManufacturerCreateView,
    ManufacturerUpdateView,
    ManufacturerDeleteView,
    driver_car,
)

urlpatterns = [
    path("", index, name="index"),

    path(
        "manufacturers/",
        ManufacturerListView.as_view(),
        name="manufacturer-list"
    ),
    path(
        "manufacturers/create",
        ManufacturerCreateView.as_view(),
        name="manufacturer-create"
    ),
    path(
        "manufacturers/<int:pk>/update",
        ManufacturerUpdateView.as_view(),
        name="manufacturer-update"
    ),
    path(
        "manufacturers/<int:pk>/delete",
        ManufacturerDeleteView.as_view(),
        name="manufacturer-delete"
    ),
    path(
        "cars/",
        CarListView.as_view(),
        name="car-list"
    ),
    path(
        "cars/<int:pk>/",
        CarDetailView.as_view(),
        name="car-detail"
    ),
    path(
        "cars/create",
        CarCreateView.as_view(),
        name="car-create"
    ),
    path(
        "cars/<int:pk>/update",
        CarUpdateView.as_view(),
        name="car-update"
    ),
    path(
        "car/<int:pk>/delete",
        CarDeleteView.as_view(),
        name="car-delete"
    ),
    path(
        "drivers/",
        DriverListView.as_view(),
        name="driver-list"
    ),
    path(
        "drivers/<int:pk>/",
        DriverDetailView.as_view(),
        name="driver-detail"
    ),
    path(
        "drivers/create",
        DriverCreateView.as_view(),
        name="driver-create"
    ),
    path(
        "drivers/<int:pk>/license",
        DriverLicenseUpdate.as_view(),
        name="driver-license"
    ),
    path(
        "drivers/<int:pk>/delete",
        DriverDeleteView.as_view(),
        name="driver-delete"
    ),
    path(
        "cars/<int:pk>/changes",
        driver_car,
        name="driver-car"
    ),
]

app_name = "taxi"

taxi_service/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("taxi.urls", namespace="taxi")),
    path("accounts/", include("django.contrib.auth.urls")),
    path('__debug__/', include('debug_toolbar.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

taxi/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.urls import reverse


class Manufacturer(models.Model):
    name = models.CharField(max_length=255, unique=True)
    country = models.CharField(max_length=255)

    class Meta:
        ordering = ["name"]

    def __str__(self):
        return f"{self.name} {self.country}"


class Driver(AbstractUser):
    license_number = models.CharField(max_length=255, unique=True)

    class Meta:
        verbose_name = "driver"
        verbose_name_plural = "drivers"

    def __str__(self):
        return f"{self.username} ({self.first_name} {self.last_name})"

    def get_absolute_url(self):
        return reverse("taxi:driver-detail", kwargs={'pk': self.pk})


class Car(models.Model):
    model = models.CharField(max_length=255)
    manufacturer = models.ForeignKey(Manufacturer, on_delete=models.CASCADE)
    drivers = models.ManyToManyField(Driver, related_name="cars")

    class Meta:
        ordering = ["manufacturer"]

    def __str__(self):
        return self.model

taxi/views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin

from .form import DriverCreationForm, DriverLicenseUpdateForm, CarForm, CarSearchForm
from .models import Driver, Car, Manufacturer


@login_required
def index(request):
    """View function for the home page of the site."""

    num_drivers = Driver.objects.count()
    num_cars = Car.objects.count()
    num_manufacturers = Manufacturer.objects.count()

    num_visits = request.session.get("num_visits", 0)
    request.session["num_visits"] = num_visits + 1

    context = {
        "num_drivers": num_drivers,
        "num_cars": num_cars,
        "num_manufacturers": num_manufacturers,
        "num_visits": num_visits + 1,
    }

    return render(request, "taxi/index.html", context=context)


class ManufacturerListView(LoginRequiredMixin, generic.ListView):
    model = Manufacturer
    context_object_name = "manufacturer_list"
    template_name = "taxi/manufacturer_list.html"
    paginate_by = 2


class ManufacturerCreateView(LoginRequiredMixin, generic.CreateView):
    model = Manufacturer
    fields = "__all__"
    success_url = reverse_lazy("taxi:manufacturer-list")


class ManufacturerUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Manufacturer
    fields = "__all__"
    success_url = reverse_lazy("taxi:manufacturer-list")


class ManufacturerDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Manufacturer
    fields = "__all__"
    success_url = reverse_lazy("taxi:manufacturer-list")
    template_name = "taxi/manufacturer_delete.html"


class CarListView(LoginRequiredMixin, generic.ListView):
    model = Car
    paginate_by = 2
    queryset = Car.objects.all().select_related("manufacturer")

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(CarListView, self).get_context_data(**kwargs)

        model = self.request.GET.get("model", "")

        context["search_form"] = CarSearchForm(
            initial={"model": model}
        )

        return context

    def get_queryset(self):
        model = self.request.GET.get("model")

        if model:
            return self.queryset.filter(model__icontains=model)

        return self.queryset


class CarDetailView(LoginRequiredMixin, generic.DetailView):
    model = Car


class CarCreateView(LoginRequiredMixin, generic.CreateView):
    model = Car
    form_class = CarForm
    success_url = reverse_lazy("taxi:car-list")


class CarUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Car
    form_class = CarForm
    success_url = reverse_lazy("taxi:car-list")


class CarDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Car
    fields = "__all__"
    success_url = reverse_lazy("taxi:car-list")
    template_name = "taxi/car_delete.html"


class DriverListView(LoginRequiredMixin, generic.ListView):
    model = Driver
    paginate_by = 2


class DriverDetailView(LoginRequiredMixin, generic.DetailView):
    model = Driver
    queryset = Driver.objects.all().prefetch_related("cars__manufacturer")


class DriverCreateView(LoginRequiredMixin, generic.CreateView):
    model = Driver
    form_class = DriverCreationForm
    success_url = reverse_lazy("taxi:driver-list")


class DriverLicenseUpdate(LoginRequiredMixin, generic.UpdateView):
    model = Driver
    form_class = DriverLicenseUpdateForm
    template_name = "taxi/driver_license_update_form.html"


class DriverDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Driver
    fields = "__all__"
    success_url = reverse_lazy("taxi:driver-list")
    template_name = "taxi/driver_delete.html"


def driver_car(request, pk):
    driver = Driver.objects.get(id=request.user.id)
    if Car.objects.get(id=pk) in driver.cars.all():
        driver.cars.remove(pk)
    else:
        driver.cars.add(pk)
    return HttpResponseRedirect(
        reverse_lazy(
            "taxi:car-detail",
            args=[pk]
        )
    )

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% block title %}<title>Taxi Service</title>{% endblock %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
          integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2"
          crossorigin="anonymous">
    <!-- Add additional CSS in static file -->
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
      <link rel="shortcut icon" href="{% static 'icon/favicon.ico' %}" type="image/x-icon" />
      <link rel="apple-touch-icon" href="{% static 'icon/apple-touch-icon.png' %}" />
      <link rel="apple-touch-icon" sizes="57x57" href="{% static 'icon/apple-touch-icon-57x57.png' %}" />
      <link rel="apple-touch-icon" sizes="72x72" href="{% static 'icon/apple-touch-icon-72x72.png' %}" />
      <link rel="apple-touch-icon" sizes="76x76" href="{% static 'icon/apple-touch-icon-76x76.png' %}" />
      <link rel="apple-touch-icon" sizes="114x114" href="{% static 'icon/apple-touch-icon-114x114.png' %}" />
      <link rel="apple-touch-icon" sizes="120x120" href="{% static 'icon/apple-touch-icon-120x120.png' %}" />
      <link rel="apple-touch-icon" sizes="144x144" href="{% static 'icon/apple-touch-icon-144x144.png' %}" />
      <link rel="apple-touch-icon" sizes="152x152" href="{% static 'icon/apple-touch-icon-152x152.png' %}" />
      <link rel="apple-touch-icon" sizes="180x180" href="{% static 'icon/apple-touch-icon-180x180.png' %}" />
</head>

<body>
<div class="container-fluid">
    <div class="row">
        <div class="col-3 shadow p-3 bg-white text-dark">

            {% block sidebar %}
                {% include "includes/sidebar.html" %}
            {% endblock %}

        </div>

        <div class="col-9 shadow p-3 bg-white text-dark">
            <div class="shadow p-3 bg-white text-dark">

            {% block content %}{% endblock %}

            {% block pagination %}
                {% include "includes/pagination.html" %}
            {% endblock %}
            </div>
        </div>
    </div>
</div>
</body>

</html>

templates/includes/pagination.html
{% load query_transform %}
{% if is_paginated %}
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item">
        <a href="?{% query_transform request page=page_obj.previous_page_number %}" class="page-link">prev</a>
      </li>
    {% endif %}
    <li class="page-item active">
      <span class="page-link">{{ page_obj.number }} of {{ paginator.num_pages }}</span>
    </li>
    {% if page_obj.has_next %}
      <li class="page-item">
        <a href="?{% query_transform request page=page_obj.next_page_number %}" class="page-link">next</a>
      </li>
    {% endif %}
  </ul>
{% endif %}

templates/includes/sidebar.html
<div class="shadow p-3 bg-white text-dark">
    <ul class="sidebar-nav list-group">
      {% if user.is_authenticated %}
        <li class="list-group-item">
            <strong>User: </strong>
            <a href="{{ user.get_absolute_url }}" class="username"> {{ user.get_username }} </a>
        <a href="{% url 'logout'%}?next={{request.path}}" class="btn btn-outline-dark btm-sm logout">Logout</a>
        </li>
      {% else %}
        <li class="list-group-item">
            <a href="{% url 'login'%}?next={{request.path}}" class="text-secondary font-weight-bolder">Login</a>
        </li>
      {% endif %}

      <br>

      <div class="list-group">
          <a href="{% url 'taxi:index' %}" class="btn btn-outline-dark"><strong>Home</strong></a>
          <br>
          <a href="{% url 'taxi:driver-list' %}" class="btn btn-outline-dark"><strong>Drivers</strong></a>
          <br>
          <a href="{% url 'taxi:car-list' %}" class="btn btn-outline-dark"><strong>Cars</strong></a>
          <br>
          <a href="{% url 'taxi:manufacturer-list' %}" class="btn btn-outline-dark"><strong>Manufacturers</strong></a>
      </div>
    </ul>
</div>

templates/taxi/car_delete.html
{% extends "base.html" %}

{% block content %}
        <h1>Delete Car</h1>

        <p>Are you sure want to delete the car:
            <strong> {{ car.model }} </strong>?
        </p>


        <form action="" method="post">
        {% csrf_token %}
        <input type="submit" value="Yes, delete" class="btn btn-danger"/>
        </form>
{% endblock %}

templates/taxi/car_detail.html
{% extends "base.html" %}

{% block content %}
      <h1>
        Model: {{ car.manufacturer.name }} {{ car.model }}
      </h1>
        <p class="font-italic"><strong>Manufacturer:</strong> {{ car.manufacturer.country }} </p>

      <div class="ml-3">
        <h4>
            Drivers
            {% if user in car.drivers.all %}
                <a href="{% url 'taxi:driver-car' pk=car.id %}" class="btn btn-danger button">Delete me for this car</a>
            {% else %}
                <a href="{% url 'taxi:driver-car' pk=car.id %}" class="btn btn-success button">Assign me to this car</a>
            {% endif %}
        </h4>

        {% for driver in car.drivers.all %}
            <hr>
            <p><strong>Username:</strong> {{ driver.username }}</p>
            <p><strong>Full name:</strong> {{ driver.first_name }} {{ driver.last_name }}</p>
            <p><strong>Email address:</strong> {{ driver.email }} </p>
            <p><strong>License number:</strong> {{ driver.license_number }}</p>
            <p class="text-muted"><strong>Id:</strong> {{driver.id}}</p>

        {% empty %}
          <p>No drivers!</p>
        {% endfor %}
      </div>
        <a href="{% url 'taxi:car-update' pk=car.id %}" class="btn btn-warning">Update</a>
        <a href="{% url 'taxi:car-delete' pk=car.id %}" class="btn btn-danger">Delete</a>
{% endblock %}

templates/taxi/car_form.html
{% extends "base.html" %}

{% load crispy_forms_filters %}

{% block content %}
    <h1>{{ object|yesno:"Update,Create" }} Car</h1>

    <form action="" method="post" novalidate>
        {% csrf_token %}
        {{ form|crispy }}

        <input class="btn btn-primary" type="submit" value="Submit">
    </form>
{% endblock %}

templates/taxi/car_list.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
      <h1>
          Car list
          <a href="{% url 'taxi:car-create' %}"
             class="btn btn-success button">
              Create
          </a>
      </h1>

        <form action="" method="get" class="form-inline">

          {{ search_form|crispy }}
            <input class="btn btn-secondary" type="submit" value="🔍">

        </form>
        <br>

      {% if car_list %}
        <table class="table">
        <thead class="thead-dark">
          <tr>
            <th scope="col">id</th>
            <th scope="col">Manufacturer</th>
            <th scope="col">Model</th>
            <th scope="col">Country</th>
            <th scope="col">Detail</th>
          </tr>
        </thead>
        <tbody>
            {% for car in car_list %}
             <tr>
                <th scope="row"> {{ car.id }} </th>
                <td class="font-weight-bolder"> {{ car.manufacturer.name }} </td>
                <td class="font-weight-bolder"> {{ car.model }} </td>
                <td class="font-weight-bolder"> {{car.manufacturer.country}} </td>
                <td> <a href="{% url "taxi:car-detail" pk=car.id %} " class="btn btn-outline-info"> Detail </a> </td>
                {% endfor %}
            </tr>
        </tbody>
        </table>
      {% else %}
        <p>There are no cars in taxi</p>
      {% endif %}
{% endblock %}

templates/taxi/driver_delete.html
{% extends "base.html" %}

{% block content %}
    <h1>Delete Driver</h1>

    <p>Are you sure want to delete the driver:
        <strong> {{ driver.username }} </strong>?
    </p>


    <form action="" method="post">
    {% csrf_token %}
    <input type="submit" value="Yes, delete" class="btn btn-danger"/>
    </form>

{% endblock %}

templates/taxi/driver_detail.html
{% extends "base.html" %}

{% block content %}
  <h1>
    Username: {{ driver.username }}
  </h1>

  <p><strong>First name:</strong> {{ driver.first_name }}</p>
  <p><strong>Last name:</strong> {{ driver.last_name }}</p>
  <p><strong>License number:</strong> {{ driver.license_number }}
      <a href="{% url 'taxi:driver-license' pk=driver.id %}"
         class="btn btn-secondary btn-sm">Update
      </a>
  </p>
  <p><strong>Is staff:</strong> {{ driver.is_staff }}</p>

  <div class="shadow p-3 bg-white text-dark">
    <h4>Cars</h4>

    {% for car in driver.cars.all %}
        <hr>
        <p><strong>Model:</strong> {{ car.model }}</p>
        <p><strong>Manufacturer:</strong> {{ car.manufacturer.name }}</p>
        <p class="text-muted"><strong>Id:</strong> {{car.id}}</p>

    {% empty %}
      <p>No cars!</p>
    {% endfor %}
  </div>
   <a href="{% url 'taxi:driver-delete' pk=driver.id %}" class="btn btn-danger">DELETE</a>
{% endblock %}

templates/taxi/driver_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
    <h1>{{ object|yesno:"Update,Create" }} Driver</h1>

    <form action="" method="post" novalidate>
        {% csrf_token %}
        {{ form|crispy }}

        <input class="btn btn-primary" type="submit" value="Submit">
    </form>
{% endblock %}

templates/taxi/driver_license_update_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
    <h1>Update driver license number</h1>

    <form action="" method="post" novalidate>
        {% csrf_token %}
        {{ form|crispy }}

        <input class="btn btn-primary" type="submit" value="Submit">
    </form>
{% endblock %}

templates/taxi/driver_list.html
{% extends "base.html" %}

{% block content %}
    <h1>
        Driver List
        <a href="{% url 'taxi:driver-create' %}"
           class="btn btn-success button">
            Create
        </a>
    </h1>
    <br>
    {% if driver_list %}
    <table class="table">
    <thead class="thead-dark">
      <tr>
        <th>ID</th>
        <th>Username</th>
        <th>First name</th>
        <th>Last name</th>
        <th>License number</th>
        <th>Detail</th>
      </tr>
    </thead>
    {% for driver in driver_list %}
      <tr>
        <td class="font-weight-bolder">{{ driver.id }}</td>
        <td class="font-weight-bolder">
                {{ driver.username }} {% if user == driver %} (Me){% endif %}
        </td>
        <td class="font-weight-bolder">{{ driver.first_name }}</td>
        <td class="font-weight-bolder">{{ driver.last_name }}</td>
        <td class="font-weight-bolder">{{ driver.license_number }}</td>
        <td> <a href="{% url "taxi:driver-detail" pk=driver.id %} " class="btn btn-outline-info"> Detail </a> </td>
      </tr>
    {% endfor %}

    </table>
    {% else %}
      <p>There are no drivers in the service.</p>
    {% endif %}
{% endblock %}

templates/taxi/index.html
{% extends "base.html" %}

{% block content %}
        <h1>Taxi Service Home</h1>
        <p>Welcome to Best Taxi Ever!</p>

        <h2>Dynamic content</h2>
        <p>The Taxi service has the following record counts:</p>
        <ul>
            <li><strong>Cars:</strong> {{ num_cars }}</li>
            <li><strong>Drivers:</strong> {{ num_drivers }}</li>
            <li><strong>Manufacturers:</strong> {{ num_manufacturers }}</li>
        </ul>

        <p>You have visited this page
            {{ num_visits }} time{{ num_visits|pluralize }}.
        </p>

{% endblock %}

templates/taxi/manufacturer_delete.html
{% extends "base.html" %}

{% block content %}
    <h1>Delete Manufacturer</h1>

    <p>Are you sure want to delete the manufacturer: {{ manufacturer.name }}?</p>
    <p><i>All Cars with this manufacturer will be deleted!</i></p>

    <form action="" method="post">
    {% csrf_token %}
    <input type="submit" value="Yes, delete" class="btn btn-danger"/>
    </form>

{% endblock %}

templates/taxi/manufacturer_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
    <h1>{{ object|yesno:"Update,Create" }} Manufacturer</h1>

    <form action="" method="post" novalidate>
        {% csrf_token %}
        {{ form|crispy }}

        <input class="btn btn-primary" type="submit" value="Submit">
    </form>
{% endblock %}

templates/taxi/manufacturer_list.html
{% extends "base.html" %}

{% block content %}
    <h1>Manufacturer List
        <a href="{% url 'taxi:manufacturer-create' %}"
           class="btn btn-success button">
            Create
        </a>
    </h1>
    <br>

    {% if manufacturer_list %}
      <table class="table">
      <thead class="thead-dark">
        <tr>
          <th>ID</th>
          <th>Name</th>
          <th>Country</th>
          <th>Update</th>
          <th>Delete</th>
        </tr>
      </thead>
        {% for manufacturer in manufacturer_list %}
            <tr>
              <td class="font-weight-bolder">
                  {{ manufacturer.id }}
              </td>
              <td class="font-weight-bolder">
                  {{ manufacturer.name }}
              </td>
              <td class="font-weight-bolder">
                  {{ manufacturer.country }}
              </td>
              <td>
                  <a href="{% url 'taxi:manufacturer-update' pk=manufacturer.id %}" class="btn btn-outline-secondary btn-sm">UPDATE</a>
              </td>
              <td>
                  <a href="{% url 'taxi:manufacturer-delete' pk=manufacturer.id %}" class="btn btn-outline-danger btn-sm">DELETE</a>
              </td>
          </tr>
        {% endfor %}
      </table>

    {% else %}
        <p>There are no manufacturers in the service.</p>
    {% endif %}
{% endblock %}